name: buildkit
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: loganharbour-arctest

    container:
      image: moby/buildkit:latest

    steps:
      #- name: Debug pause
      #  if: always()
      #  run: sleep 3600
      - name: show host
        run: echo $BUILDKIT_HOST
      - name: test connection
        run: buildctl --addr "$BUILDKIT_HOST" debug workers
