name: Actions Runner Controller Demo
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: loganharbour-arctest

    container:
      image: ubuntu:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Show Ubuntu version
        run: uname -a

      - name: Run a simple script
        run: echo "Hello from GitHub Actions on Ubuntu"
